f1_stats/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('race_stats.urls')),
]

race_stats/urls.py
from django.urls import path
from . import views

# from .views import races
# from .views import drivers
# from .views import constructors
# from .views import circuits
# from .views import seasons
# from .views import status
# from .views import constructor_standings
# from .views import constructor_results
# from .views import driver_standings
# from .views import sprint_results
# from .views import qualifying
# from .views import pit_stops
# from .views import lap_times
# from .views import results

app_name = 'race_stats'

urlpatterns = [
    path('', views.home, name='home'),
    path('stats/', views.stats, name='stats'),
    # path("admin/", admin.site.urls),
    # path("races/", races, name='races.html'),
    # path("drivers/", drivers, name='drivers.html'),
    # path("constructors/", constructors, name='constructors.html'),
    # path("circuits/", circuits, name='circuits.html'),
    # path("seasons/", seasons, name='seasons.html'),
    # path("status/", status, name='status.html'),
    # path("constructor_standings/", constructor_standings, name='constructor_standings.html'),
    # path("constructor_results/", constructor_results, name='constructor_results.html'),
    # path("driver_standings/", driver_standings, name='driver_standings.html'),
    # path("sprint_results/", sprint_results, name='sprint_results.html'),
    # path("qualifying/", qualifying, name='qualifying.html'),
    # path("pit_stops/", pit_stops, name='pit_stops.html'),
    # path("lap_times/", lap_times, name='lap_times.html'),
    # path("results/", results, name='results.html'),
]

templates/home.html
<!doctype html>
<html>
<head>
	<title>F1 STATS</title>
</head>
<body>
	<h1>Select a model:</h1>
  <form method="POST" action="{% url 'race_stats:stats' %}">
    {% csrf_token %}
    <label for="model-name">Select a model:</label>
    <select name="model-name" id="model-name">
      {% for model in models %}
        <option value="{{ model }}">{{ model }}</option>
      {% endfor %}
    </select>
    <input type="submit" value="Submit">
  </form>
</body>
</html>

templates/stats.html
<!doctype html>

<html>
<head>
	<title>F1 STATS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    {% load render_table from django_tables2 %}
</head>
<body>
	<h1>Stats for {{ model_name }}</h1>
    <a href="{% url 'race_stats:home' %}"><button>HOME</button></a>
	{% render_table table %}
</body>
</html>